### ISSUE TITLE
Modify Fill / Stroke Colour

### ISSUE THREAD

**Issue by mwinters-stuff** [avianey/androidsvgdrawable-plugin#18]
Hi...Great plugin, this should be part of the android plugin!!

A suggestion for a new feature, it would be nice to be able to modify colours in the svg files when creating the icons.. For example, My icons need to be RGBA ffffffc8 which means they are impossible to see in Inkscape, so to edit I have to select all, change colour to black, and then back again..

If an option was possible, eg changeColor 0x00000000, 0xffffffc8 which would change all colours of the first to the second that would be even more awesome!

Thanks.

**Comment by avianey** [comment]
Will investigate this. Might be usefull to have per-flavor color scheme.

**Comment by wintersandroid** [comment]
One of the forks has done some work on it. I have not checked it out yet..

:)

Great plugin.. moving all my projects to use it.

On 14 April 2015 at 08:23, Antoine Vianey <notifications@github.com> wrote:

> Will investigate this. Might be usefull to have per-flavor color scheme.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/avianey/androidsvgdrawable-plugin/issues/18#issuecomment-92487835>
> .
>



-- 
*Mathew Winters*
*See my other apps*
*https://play.google.com/store/apps/developer?id=Mathew+Winters
<https://play.google.com/store/apps/developer?id=Mathew+Winters>*

**Comment by avianey** [comment]
We might think about the proper way to do this...
What's the need ?
* generate multiple png of diferent color from a single svg
* generate a single png from an svg of a wrong color
* generate multiple apk with multiple styles (change color)

We can do this :
* using a json file like in the PR
* using proper XSLT to replace color
* use a custom transcoding hint from batik that will replace color on the fly (https://xmlgraphics.apache.org/batik/javadoc/org/apache/batik/transcoder/image/ImageTranscoder.html)
* using CSS ?

**Comment by wintersandroid** [comment]
Having recently had a closer look at colouring SVG icons in HTML (eg from the material design set), These icons have no fill or stroke colour set, this makes it show as black in the likes of inkscape, using CSS we can then set the color attribute when the icon is drawn.

* I think the need is to set a default colour for the icon set, which sets the colour when one is not used in the SVG..
* Then have the ability to create alternate colours - eg where the icon might be rendered in different places with a dark or light background.
