### ISSUE TITLE
The output directory is not created if it does not exist

### ISSUE THREAD

**Issue by osechet** [avianey/androidsvgdrawable-plugin#22]
I would like to use the plugin to generate the images in the build directory. It's almost working but the output directory is not created by the plugin.
1. I set the `to` option to `build/generated-sources/res`
2. I added the following command to my `build.gradle` file:

    android.sourceSets {
        main.res.srcDirs = ['src/main/res', 'build/generated-sources/res']
    }

Then when I run the build with gradle, the image files are not created and I get a compilation error since the resource ids cannot be found. If I manually create the `build/generated-sources/res` directory, the files are generated and the build completes without error.

**Comment by osechet** [comment]
I found a workaround by adding `to.mkdirs()` at the end of the `svgToPng` task definition:

    task svgToPng(type: fr.avianey.androidsvgdrawable.gradle.SvgDrawableTask) {
        ...
        to.mkdirs()
    }

But I would still prefer the plugin to do it automatically.

**Comment by avianey** [comment]
Its a good idea to generate drawable to a build/generated-sources/res directory. I'll see if I can do something to `mkdirs` automatically if the `to` directory is in the android `main.res.srcDirs`.

Also, thanks for the workaround
