### ISSUE TITLE
Useful error messages

### ISSUE THREAD

**Issue by schildbach** [avianey/androidsvgdrawable-plugin#27]
Generally, error messages should say what's wrong and idealy also give a hint how to fix it.

When I define just `from` and `to`, all I get from the plugin is
```
$ gradle svgToPng
:svgToPng FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':svgToPng'.
> java.lang.NullPointerException (no error message)
```

By trial and error I found out when I add `targetedDensities` the error changes to
```
$ gradle svgToPng
:svgToPng

org.apache.batik.transcoder.TranscoderException: null
Enclosed Exception:
Unable to transform src image
	at org.apache.batik.transcoder.image.ImageTranscoder.transcode(ImageTranscoder.java:132)
	at org.apache.batik.transcoder.XMLAbstractTranscoder.transcode(XMLAbstractTranscoder.java:142)
	at org.apache.batik.transcoder.SVGAbstractTranscoder.transcode(SVGAbstractTranscoder.java:156)
	at fr.avianey.androidsvgdrawable.SvgDrawablePlugin.transcode(SvgDrawablePlugin.java:434)
	at fr.avianey.androidsvgdrawable.SvgDrawablePlugin.transcode(SvgDrawablePlugin.java:367)
	at fr.avianey.androidsvgdrawable.SvgDrawablePlugin.execute(SvgDrawablePlugin.java:246)
	at fr.avianey.androidsvgdrawable.gradle.SvgDrawableTask.svgToDrawable(SvgDrawableTask.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
    [...]
org.apache.batik.transcoder.TranscoderException: null
```

Both messages are not helpful to the user.

**Comment by avianey** [comment]
Well, I think I'll need the content of your from diectory (if you manage to extract the file responsible for this error)... It looks like an Apache Batik bug :-(

**Comment by schildbach** [comment]
I will see if I can upload an SVG later.

Note that this issue is not about finding or fixing bugs in Batik or in my SVG, but to provide better error messages. For example if your theory is right, why doesn't it print the name of the SVG? With the above messages, I don't even know if I perhaps have a syntax error in my configuration. Did it ever start scanning for SVGs? Etc.

**Comment by avianey** [comment]
Well I'm not going to catch RuntimeException everywhere... but at least this will be usefull to have the name of the SVG printed :+1:

**Comment by schildbach** [comment]
Thanks for the improvement. Does that also cover my first example?

**Comment by schildbach** [comment]
FWIW, here is the SVG that causes the "null" message:

```
<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" version="1.1" width="1024px" height="1024px" viewBox="-32 -32 1088 1088">
	<defs>
		<linearGradient id="background-gradient" x1="0%" y1="0%" x2="0%" y2="100%">
			<stop offset="0%" style="stop-color:#f0c410" />
			<stop offset="100%" style="stop-color:#f0c410" />
		</linearGradient>
		<linearGradient id="symbol-gradient" x1="0%" y1="0%" x2="0%" y2="100%">
			<stop offset="0%" style="stop-color:#40a33f" />
			<stop offset="100%" style="stop-color:#40a33f" />
		</linearGradient>
		<filter id="background-shadow">
			<feOffset result="offsetOut" in="SourceGraphic" dx="0" dy="32" />
			<feColorMatrix result="matrixOut" in="offsetOut" type="matrix"
				values="0.15 0 0 0 0 0 0.15 0 0 0 0 0 0.15 0 0 0 0 0 1 0" />
			<feGaussianBlur result="blurOut" in="matrixOut" stdDeviation="32" />
			<feBlend in="SourceGraphic" in2="blurOut" mode="normal" />
		</filter>
	</defs>

	<!-- background -->
	<circle cx="512" cy="512" r="512" fill="url(#symbol-gradient)" />
	<circle cx="512" cy="512" r="400" fill="url(#background-gradient)" filter="url(#background-shadow)" />

	<!-- H -->
	<path d="M 354,787 v -554 m 0,266 h 311 m 0,288 v -554" style="fill:none;stroke:#40a33f;stroke-width:104" />
</svg>
```

**Comment by avianey** [comment]
Will see what regular cmd line batik transcoding does with this file...

**Comment by schildbach** [comment]
I can do that myself to save you time. Can you just point me to the "cmd line Batik"? I didn't find such a tool, just a library.

Strangely, the SVG seems to work fine with

- eog (Eye of Gnome)
- Gimp
- the stone-age old "batik-maven-plugin" which uses an equally old Batik version.

**Comment by avianey** [comment]
You can try the conversion using this method : https://xmlgraphics.apache.org/batik/tools/rasterizer.html

**Comment by schildbach** [comment]
It fails with all recent Batik versions (same exception). I experimented and if I remove `filter="url(#background-shadow)"` the problem goes away. Do you see any obvious problem with the shadow?

**Comment by schildbach** [comment]
More testing: if I remove `<feBlend in="SourceGraphic" in2="blurOut" mode="normal" />` but keep the rest the problem goes away as well, but of course the image doesn't look like I want.

**Comment by schildbach** [comment]
I [filed the issue](https://issues.apache.org/jira/browse/BATIK-1122) with Batik.
