### ISSUE TITLE
Generate density specific pngs?

### ISSUE THREAD

**Issue by vovkab** [avianey/androidsvgdrawable-plugin#31]
Maybe I'm missing something, but how do I create density specific png?

When you create png's usually you want to have at least 2 svg. One for mdpi and another for hdpi. This way images that have straight lines will not be blurry.

So here can be a few ways to create other densities from mdpi and hdpi files:

====== (1) ======
mdpi x1 -> mdpi
hdpi x1 -> hdpi
mdpi x2 -> xhdpi
mdpi x3 -> xxhdpi

or 
====== (2) ======
mdpi x1 -> mdpi
hdpi x1 -> hdpi
mdpi x2 -> xhdpi
hdpi x2 -> xxhdpi

For now I just need to do (1) to avoid blurry image.

Right now if you use only 
* mdpi -> hdpi will be blurry.
* hdpi -> mdpi and xhdpi will be blurry

**Comment by avianey** [comment]
You can already achieve this by using two tasks :
```
task mdpiToPng(type: fr.avianey.androidsvgdrawable.gradle.SvgDrawableTask) {
    from = file('src/main/svg-mdpi')
    to = file('build/generated/res/main')
    targetedDensities = ['mdpi', 'xhdpi', 'xxhdpi']
    outputFormat = 'PNG'
}
```
and
```
task hdpiToPng(type: fr.avianey.androidsvgdrawable.gradle.SvgDrawableTask) {
    from = file('src/main/svg-hdpi')
    to = file('build/generated/res/main')
    targetedDensities = ['hdpi']
    outputFormat = 'PNG'
}
```
Will do the trick for case (1) and (2) with just a little modification.
Enjoy :-)

**Comment by vovkab** [comment]
Thanks. 

It is close but it is not there yet. 
Hdpi can be there and also can be missing. With this two task it is only this or only that, there is no in between.

**Comment by avianey** [comment]
You can create a third task for svg that exists in hdpi or mdpi only...
