### ISSUE TITLE
Plugin does not work with com.android.tools.build:gradle:2.0.0-alpha9

### ISSUE THREAD

**Issue by mknudsen** [avianey/androidsvgdrawable-plugin#49]
The plugin does not seem to work with the 2.0.0-alpha9 of the android gradle plugin.

When I use `buildToolsVersion '23.0.2'` and `classpath 'com.android.tools.build:gradle:2.0.0-alpha9'` I get errors like these:

> Error:(47, 26) No resource found that matches the given name (at 'src' with value '@drawable/ic_my_icon').

My task definition looks like this:

```
final String generatedResourcesDir = 'src/main/res-generated'

task svgToPng(type: SvgDrawableTask) {
    from = files('src/main/svg-png')
    to = file(generatedResourcesDir)
    createMissingDirectories = true
    overwriteMode = 'always'
    targetedDensities = ['mdpi', 'hdpi', 'xhdpi', 'xxhdpi', 'xxxhdpi']
    outputFormat = 'PNG'
}

clean.doFirst {
    delete fileTree(dir: generatedResourcesDir, include: '**/*.png').getFiles()
}
```

The error can be reproduced using the current [canary version of Android Studio 2.0](http://tools.android.com/download/studio/canary).

**Comment by avianey** [comment]
thanks for feedback, will work on it soon

**Comment by avianey** [comment]
I'm not able to reproduce with the canary and build tools 2.0.0-alpha9

I use a generated dir added as source set :

```gradle
    sourceSets {
        main.res.srcDirs = [main.res.srcDirs, "build/generated/res/main"]
    }
```

Where I generate the resources like this :

```gradle
task svgToPng(type: fr.avianey.androidsvgdrawable.gradle.SvgDrawableTask) {
    from = files('src/main/svg')
    to = file('build/generated/res/main')
    createMissingDirectories = true
    overwriteMode = 'ifModified'
    targetedDensities = ['ldpi', 'mdpi', 'hdpi', 'xhdpi', 'xxhdpi', 'xxxhdpi']
    ninePatchConfig = file('src/main/svg/9patch.json')
}
```

I can generate the app without problem, with or without clean... :-(

**Comment by avianey** [comment]
after upgrading to the canary, I made a File > Invalidate cache & Restart and I had to upgrade the build tool then... Maybe it's just that...

**Comment by avianey** [comment]
Did you manage to have it work

**Comment by mknudsen** [comment]
Hey! I've managed to get the plugin to work with the new Android Studio based on a newly generated project and your example project. I guess I've messed up some paths in my larger project, sorry for the mess.

**Comment by avianey** [comment]
thx for feedback
