### ISSUE TITLE
Gradle up-to-date check doesn't work reliably

### ISSUE THREAD

**Issue by schildbach** [avianey/androidsvgdrawable-plugin#56]
```
task svgToPng(type: fr.avianey.androidsvgdrawable.gradle.SvgDrawableTask) {
    from = files('graphics')
    to = file('res')
    targetedDensities = ['hdpi', 'xhdpi', 'xxhdpi']
    outputFormat = 'PNG'
    outputType = 'mipmap'
}
```

My `graphics` folder contains three files:

```
graphics/ic_oeffi_directions_color_48dp-mdpi.svg
graphics/ic_oeffi_plans_color_48dp-mdpi.svg
graphics/ic_oeffi_stations_color_48dp-mdpi.svg
```

I removed all of the generated images. Then ran

```
$ gradle svgToPng
Incremental java compilation is an incubating feature.
:oeffi:svgToPng UP-TO-DATE

BUILD SUCCESSFUL
```

And if I try to build my whole project the launcher icons are missing and the build fails. I assume that's a bug in the plugin. When I try to switch `res` to `res2` it generates the images there no prob.

More info:

```
$ gradle --version

------------------------------------------------------------
Gradle 2.10
------------------------------------------------------------

Build time:   2016-01-26 15:17:49 UTC
Build number: none
Revision:     UNKNOWN

Groovy:       2.4.5
Ant:          Apache Ant(TM) version 1.9.6 compiled on July 8 2015
JVM:          1.8.0_91 (Oracle Corporation 25.91-b14)
OS:           Linux 4.4.0-31-generic amd64
```

**Comment by avianey** [comment]
Having the same `gradle --version` I'm not able to reproduce using the sample project in which I created the exact same use case as you provide... Deleting one, two, all generated resources into `res` lead to a correct up-to-date check with the task being re-executed. Running the build twice prints UP-TO-DATE as expected...

If you're able to reproduce using the sample gradle project, don't hesitate to PR with your modification...

**Comment by schildbach** [comment]
I'll see if I can reproduce. For now, I worked around the issue by removing the <projectdir>/.gradle/<gradle-version> directory which triggers the up-to-date check and rebuilds the icons for me.

**Comment by avianey** [comment]
Try to see if adding the generated files you deleted manually to the task outputs like done here https://docs.gradle.org/current/userguide/more_about_tasks.html :
```
task transform {
    ext.srcFile = file('mountains.xml')
    ext.destDir = new File(buildDir, 'generated')
    inputs.file srcFile
    outputs.dir destDir
    doLast {
        println "Transforming source file."
        destDir.mkdirs()
        def mountains = new XmlParser().parse(srcFile)
        mountains.mountain.each { mountain ->
            def name = mountain.name[0].text()
            def height = mountain.height[0].text()
            def destFile = new File(destDir, "${name}.txt")
            destFile.text = "$name -> ${height}\n"
        }
    }
}
```
when added manually like this, the plugin does not override the inputs & outputs, so you can see if it works as expected...

**Comment by avianey** [comment]
Was able to reproduce when two consecutives tasks outputs to the save dir...
