### ISSUE TITLE
Support for android.library.plugin

### ISSUE THREAD

**Issue by avianey** [avianey/androidsvgdrawable-plugin#57]
Being able to generate resources when using 
```
apply plugin: 'com.android.library'
```

**Comment by multiholle** [comment]
How can I reference the changes you made in my project gradle files? Could you provide a new release version?

**Comment by avianey** [comment]
I need to test it before, you can still run it as demonstrated in the libgdx sample
```preBuild.dependsOn yourSvgPngTaskName```
without the ```apply plugin```
