### ISSUE TITLE
8.0.0 gradle plugin unavailable?

### ISSUE THREAD

**Issue by barney2k7** [avianey/androidsvgdrawable-plugin#76]
While the [CHANGELOG lists a gradle plugin version 8.0.0](https://github.com/avianey/androidsvgdrawable-plugin/blob/master/CHANGELOG.md), that version doesn't seem to actually be published anywhere,
neither [Maven Central](https://search.maven.org/artifact/fr.avianey.androidsvgdrawable/gradle-plugin) ([alt link](https://repo1.maven.org/maven2/fr/avianey/androidsvgdrawable/gradle-plugin/)) nor [Gradle Plugins Portal](https://plugins.gradle.org/search?term=fr.avianey.androidsvgdrawable%3Agradle-plugin).
Is it available anywhere else, or can it be published? Or are there still issues with gradle 8.x itself?
Thanks!

**Comment by avianey** [comment]
Hi @barney2k7 
You have to checkout the latest commit and build from sources. It will make the plugin available from your local maven repository.
I'll keep you updated if I make it available in gradle repo
Best

**Comment by barney2k7** [comment]
Hi @avianey 
thank you for the quick response
